add `WIN95FA`
fontsource/font-files pull request #45
Opened 2023-10-13 13:37 UTC by ceetee

2023-10-15 02:28 UTC, ayuhito requested changes
Thanks for the PR! Just a couple changes to make before it is good to go!

2023-10-15 02:28 UTC, ayuhito commented on fonts/other/win95fa/LICENSE
> +Copyright (c) <dates>, <additional Copyright Holder> (<URL|email>).
This section should be removed since the original author didn't seem to remove this boilerplate anyways,

2023-10-15 02:28 UTC, ayuhito commented on fonts/other/win95fa/metadata.json
> +  "source": "https://fontsarena.com/wp-content/uploads/2020/01/W95FA.zip",
```suggestion
  "source": "https://fontsarena.com/w95fa-by-alina-sava/",
```

2023-10-15 19:55 UTC, ceetee commented
Thanks for the comments, updated.

2023-10-16 00:15 UTC, ayuhito approved these changes
Awesome! Looks good to me. You should see this published by the end of the week.

2023-10-16 00:16 UTC, merged