Add Geist Mono Font
fontsource/font-files pull request #56
Opened 2023-12-19 13:44 UTC by 0xJamin

This PR adds [Geist Mono ](https://github.com/vercel/geist-font) to the list of font files

2023-12-19 14:35 UTC, ayuhito requested changes
Looks good, thanks for the PR! Just some changes needed for the license attributions. Can we also move the folder from the root of the monorepo to `fonts/other`?

2023-12-19 14:35 UTC, ayuhito commented on geist-mono/metadata.json
> +    "url": "https://openfontlicense.org/",
Should update this to [Github link](https://github.com/vercel/geist-font/blob/main/LICENSE.TXT).

2023-12-19 15:24 UTC, 0xJamin commented
> Looks good, thanks for the PR! Just some changes needed for the license attributions. Can we also move the folder from the root of the monorepo to `fonts/other`?

Hi @ayuhito  Changes updated

2023-12-26 23:30 UTC, ayuhito commented
Sorry for the late review. The tests are not passing since the folder is missing a LICENSE file. Can you copy over the license file from the original repository? That should clear the tests.

2023-12-27 16:03 UTC, 0xJamin commented
Hi @ayuhito  I have updated the LICENSE

2024-01-11 19:47 UTC, ayuhito approved these changes
Sorry for the delay. I ended up travelling. Thanks for the PR!

2024-01-11 19:47 UTC, merged