feat(font): add sn-pro (#65)
fontsource/font-files pull request #69
Opened 2024-04-24 04:38 UTC by acnebs

2024-04-24 14:09 UTC, ayuhito requested changes
Everything looks good to me! Just a small nit before I can merge this 🎉

2024-04-24 14:09 UTC, ayuhito commented on fonts/other/sn-pro/metadata.json
> +    "url": "https://github.com/supernotes/sn-pro",
```suggestion
    "url": "https://github.com/supernotes/sn-pro/blob/main/OFL.txt",
```

This should be a link to the license directly.

2024-04-25 06:42 UTC, acnebs commented
Done!

2024-04-25 13:26 UTC, ayuhito approved these changes
LGTM! Thank you 🎉

2024-04-25 13:26 UTC, merged

2024-04-25 16:36 UTC, DIYgod commented
Thank you for your contribution, but I got a 500 error when visiting [sn pro page](https://fontsource.org/fonts/sn-pro), and I didn't get any further error messages in the console.

2024-04-25 20:25 UTC, ayuhito commented
It's up now. It takes around 2-8 hours for our caches to expire on the API service and so while our search indexes update instantly, we haven't got anything setup to invalidate the API caches.